#!/bin/zsh

bar=(
  color=0x00000000
  border_color=0x00000000
  position=top
  height=27
  notch_display_height=0
  margin=10
  y_offset=5
  corner_radius=10
  border_width=0
  blur_radius=50
  padding_left=0
  padding_right=0
  notch_width=200
  notch_offset=0
  display=all
  hidden=off
  topmost=off
  sticky=on
  font_smoothing=off
  shadow=on
)

sketchybar --bar "${bar[@]}"

default=(
  background.color=0x7721262d
  background.padding_left=5
  background.padding_right=5
  background.corner_radius=5
  background.height=20
  icon.font="Hack Nerd Font Mono:Regular:13.0"
  label.font="Hack Nerd Font Mono:Regular:13.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=10
  icon.padding_right=5
  label.padding_left=5
  label.padding_right=10
)

sketchybar --default "${default[@]}"

source "$CONFIG_DIR/items/aerospace.zsh" left

# source "$CONFIG_DIR/items/debugger.zsh" e

source "$CONFIG_DIR/items/clock.zsh" right
source "$CONFIG_DIR/items/volume.zsh" right
source "$CONFIG_DIR/items/battery.zsh" right

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# set focused workspace on startup
focused_workspace="$(aerospace list-workspaces --focused)"
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$focused_workspace"

