#!/bin/zsh

bar=(
  color=0x88000000
  border_color=0x00000000
  position=bottom
  height=30
  notch_display_height=0
  margin=10
  y_offset=5
  corner_radius=5
  border_width=0
  blur_radius=10
  padding_left=0
  padding_right=0
  notch_width=200
  notch_offset=0
  display=all
  hidden=off
  topmost=off
  sticky=on
  font_smoothing=off
  shadow=on
)

sketchybar --bar "${bar[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="Hack Nerd Font Mono:Regular:16.0"
  label.font="Hack Nerd Font Mono:Regular:16.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=2
  icon.padding_right=2
  label.padding_left=2
  label.padding_right=2
)

sketchybar --default "${default[@]}"

source "$CONFIG_DIR/items/aerospace.zsh" left
source "$CONFIG_DIR/items/chevron.zsh" left
source "$CONFIG_DIR/items/front_app.zsh" left

source "$CONFIG_DIR/items/debugger.zsh" e

source "$CONFIG_DIR/items/clock.zsh" right
source "$CONFIG_DIR/items/volume.zsh" right
source "$CONFIG_DIR/items/battery.zsh" right

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
