#!/bin/zsh

THEME_COLOR_0=0x00000000
THEME_COLOR_1=0xff000000
THEME_COLOR_2=0xffffffff
THEME_COLOR_3=0x70ffffff

bar=(
  # border_color="$THEME_COLOR_0"
  color=0xf0000000
  position=top
  height=33
  notch_display_height=0
  margin=0
  y_offset=0
  corner_radius=0
  border_width=0
  blur_radius=0
  padding_left=15
  padding_right=15
  notch_width=200
  notch_offset=0
  display=all
  hidden=off
  topmost=off
  sticky=on
  font_smoothing=off
  shadow=off
)

sketchybar --bar "${bar[@]}"

default=(
  background.border_color="$THEME_COLOR_3"
  background.border_width=1
  background.color="$THEME_COLOR_0"
  background.corner_radius=2
  background.height=22
  background.padding_left=5
  background.padding_right=5
  icon.color="$THEME_COLOR_2"
  icon.font="Hack Nerd Font Mono:Regular:11.0"
  icon.padding_left=10
  icon.padding_right=5
  label.color="$THEME_COLOR_2"
  label.font="Hack Nerd Font Mono:Regular:11.0"
  label.padding_left=5
  label.padding_right=10
)

sketchybar --default "${default[@]}"

source "$CONFIG_DIR/items/aerospace.zsh" left

# source "$CONFIG_DIR/items/debugger.zsh" e

source "$CONFIG_DIR/items/clock.zsh" right
source "$CONFIG_DIR/items/battery.zsh" right
source "$CONFIG_DIR/items/volume.zsh" right

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# set focused workspace on startup
focused_workspace="$(aerospace list-workspaces --focused)"
sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$focused_workspace"

